# Powerlevel 9K/10K Theme Settings
POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\UE0BC"
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="\UE0BC"
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="\UE0BA"
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="\UE0BA"

# DIR
POWERLEVEL9K_DIR_HOME_BACKGROUND="green"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="blue"

# DIR_WRITABLE
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"

# COMMAND_EXECUTION_TIME
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='cyan'

# VCS
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="green"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="202" # orange
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="yellow"
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=""

# Status
POWERLEVEL9K_STATUS_OK_BACKGROUND="black"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_CARRIAGE_RETURN_ICON=""

# Time
POWERLEVEL9K_TIME_BACKGROUND="white"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"

# Battery
# POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="clear"
# POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="yellow"
# POWERLEVEL9K_BATTERY_CHARGED="green"
# POWERLEVEL9K_BATTERY_DISCONNECTED="$DEFAULT_COLOR"
# POWERLEVEL9K_BATTERY_LOW_COLOR="red"
# POWERLEVEL9K_BATTERY_LOW_THRESHOLD="15"

# Date
POWERLEVEL9K_DATE_ICON=""

# Layout
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{red}\uF054\uF054%F{white} "
POWERLEVEL9K_PROMPT_ON_NEWLINE="true"

# Prompts
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writeable_joined vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs_joined command_execution_time time)
