# POWERLEVEL10K THEME SETTINGS

# General
POWERLEVEL9K_MODE='nerdfont-complete'

# Directories
POWERLEVEL9K_DIR_FOREGROUND='white'
POWERLEVEL9K_DIR_BACKGROUND='clear'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='012'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='clear'
POWERLEVEL9K_DIR_PATH_SEPARATOR='%F{008}/%F{cyan}'

POWERLEVEL9K_HOME_ICON='\uf015 '
POWERLEVEL9K_DIR_HOME_FOREGROUND='green'
POWERLEVEL9K_DIR_HOME_BACKGROUND='clear'

POWERLEVEL9K_HOME_SUB_ICON='\uf07c '
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='012'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='clear'

POWERLEVEL9K_ETC_ICON='\uf013 '
POWERLEVEL9K_DIR_ETC_FOREGROUND='blue'
POWERLEVEL9K_DIR_ETC_BACKGROUND='clear'

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND='red'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='clear'

POWERLEVEL9K_SHORTEN_DELIMITER='%F{008} …%F{008}'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY='none'

# VCS
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='clear'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='clear'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='166'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='clear'

POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
POWERLEVEL9K_VCS_GIT_ICON=''

# Status
POWERLEVEL9K_CARRIAGE_OK_ICON='\uf00c'
POWERLEVEL9K_CARRIAGE_RETURN_ICON='\uf00d'

POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='clear'
POWERLEVEL9K_STATUS_OK_BACKGROUND='clear'
POWERLEVEL9K_STATUS_BACKGROUND='clear'

POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='cyan'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
POWERLEVEL9K_EXECUTION_TIME_ICON='\uf254'

# NVM
POWERLEVEL9K_NVM_FOREGROUND='green'
POWERLEVEL9K_NVM_BACKGROUND='clear'

# Time
POWERLEVEL9K_TIME_FOREGROUND='white'
POWERLEVEL9K_TIME_BACKGROUND='clear'
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

# OS Icons
POWERLEVEL9K_OS_ICON_FOREGROUND='cyan'
POWERLEVEL9K_OS_ICON_BACKGROUND='clear'

POWERLEVEL9K_LINUX_ARCH_ICON='\uf303'
POWERLEVEL9K_LINUX_FEDORA_ICON='\uf30b'
POWERLEVEL9K_LINUX_MANJARO_ICON='\uf312'
POWERLEVEL9K_LINUX_UBUNTU_ICON='\uf31b'

# Prompt Setup
# Promt Setup is done at the very end, to ensure that all custom set icons are rendered correctly icons
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' \uf63d  '

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{008}\uf054%F{008}'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writeable_joined vcs)

POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%F{008}\uf053%F{008}'
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time)
