# Powerlevel 9K/10K Theme Settings
POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_DIR_ETC_BACKGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='white'
POWERLEVEL9K_DIR_HOME_BACKGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='white'

## VCS
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='202' # orange
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''

## Status
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_STATUS_CROSS=true

## Time
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_TIME_ICON=""

## Battery
POWERLEVEL9K_BATTERY_CHARGING="yellow"
POWERLEVEL9K_BATTERY_CHARGED="green"
POWERLEVEL9K_BATTERY_DISCONNECTED="$DEFAULT_COLOR"
POWERLEVEL9K_BATTERY_LOW_COLOR="red"
POWERLEVEL9K_BATTERY_LOW_THRESHOLD="15"

## Date
POWERLEVEL9K_DATE_ICON=""

## Layout
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "
POWERLEVEL9K_PROMPT_ON_NEWLINE="true"

## Prompts
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir_writable dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time date battery)
